X(SCIDB4GEO_ERR_POSTGRES_CONNECTION_FAILED,         SCIDB_USER_ERROR_CODE_START+ 1,  "Cannot connect to Postgres system catalog")
X(SCIDB4GEO_ERR_UNKNOWN_SRS,                        SCIDB_USER_ERROR_CODE_START+ 2,  "Unknown spatial reference system")
X(SCIDB4GEO_ERR_INVALID_AFFINETRANSFORM_STRING,     SCIDB_USER_ERROR_CODE_START+ 3,  "Cannot derive affine transformation parameters from string")
X(SCIDB4GEO_ERR_UNKNOWN,                            SCIDB_USER_ERROR_CODE_START+ 4,  "Error")
X(SCIDB4GEO_ERR_SRS_ALREADY_EXISTING,               SCIDB_USER_ERROR_CODE_START+ 5,  "Spatial reference system already exists")
X(SCIDB4GEO_ERR_UNKNOWN_DIMENSIONNAME,              SCIDB_USER_ERROR_CODE_START+ 6,  "Unknown dimension")
X(SCIDB4GEO_ERR_UNKNOWN_ARRAYNAME,                  SCIDB_USER_ERROR_CODE_START+ 7,  "Unknown array")
X(SCIDB4GEO_ERR_INCONSISTENT_DBSTATE,               SCIDB_USER_ERROR_CODE_START+ 8,  "Reference metadata corrupted")
X(SCIDB4GEO_ERR_UNDECLARED_ARRAY,                   SCIDB_USER_ERROR_CODE_START+ 9,  "Array with given name does not exist")
X(SCIDB4GEO_ERR_UNDECLARED_DIMENSION,               SCIDB_USER_ERROR_CODE_START+ 10, "Dimension with given name does not exist")              
X(SCIDB4GEO_ERR_SINGULARMATRIX,              	    SCIDB_USER_ERROR_CODE_START+ 11, "Matrix is singular")   
X(SCIDB4GEO_ERR_INVALIDDIMENSION,              	    SCIDB_USER_ERROR_CODE_START+ 12, "Dimension is not valid")   
X(SCIDB4GEO_ERR_INVALIDATTRIBUTE,              	    SCIDB_USER_ERROR_CODE_START+ 13, "Attribute is not valid")  
X(SCIDB4GEO_ERR_INVALIDINPUT,              	    SCIDB_USER_ERROR_CODE_START+ 14, "Invalid Input") 
X(SCIDB4GEO_ERR_SRSMISMATCH,              	    SCIDB_USER_ERROR_CODE_START+ 15, "Spatial reference systems of arrays do not match") 
X(SCIDB4GEO_ERR_ARRAYEXISTS,              	    SCIDB_USER_ERROR_CODE_START+ 16, "Array already exists") 
X(SCIDB4GEO_ERR_UNDECLARED_ATTRIBUTE,               SCIDB_USER_ERROR_CODE_START+ 17, "Attribute with given name does not exist")  